# Generated by Django 5.0.10 on 2024-12-10 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_lv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_1', models.CharField(max_length=500)),
                ('cate_1_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category_lv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_2', models.CharField(max_length=500)),
                ('cate_2_image', models.ImageField(null=True, upload_to='')),
                ('cate_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category_lv1')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500)),
                ('user_birth', models.DateField()),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=500)),
                ('prod_price', models.IntegerField()),
                ('prod_discount', models.IntegerField()),
                ('prod_num_available', models.IntegerField()),
                ('prod_sold', models.IntegerField()),
                ('prod_num_rating', models.IntegerField()),
                ('prod_cate_lv1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category_lv1')),
                ('prod_cate_lv2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category_lv2')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_image', models.ImageField(null=True, upload_to='')),
                ('is_avatar', models.BooleanField(default=False)),
                ('prod_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
