# Generated by Django 5.0.10 on 2024-12-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_lv1_cate_1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_unit_type',
            field=models.CharField(choices=[('Hộp', 'Hộp'), ('Tuýt', 'Tuýt'), ('Ống', 'Ống'), ('Viên', 'Viên')], max_length=50, null=True),
        ),
    ]
