# Generated by Django 5.0.10 on 2024-12-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_prod_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_lv2',
            name='num_products',
            field=models.IntegerField(default=0),
        ),
    ]
