# Generated by Django 5.0.10 on 2024-12-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_lv2_num_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='prod_cate_lv1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category_lv1'),
        ),
        migrations.AddField(
            model_name='product_image',
            name='prod_cate_lv2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category_lv2'),
        ),
    ]
