# Generated by Django 5.0.10 on 2024-12-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image_prod_cate_lv1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='prod_cate_lv1',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='prod_cate_lv2',
        ),
    ]
