# Generated by Django 5.0.10 on 2024-12-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_prod_country_product_prod_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=100)),
                ('order_total', models.IntegerField()),
                ('order_method', models.CharField(max_length=100)),
                ('order_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_receiver_name', models.CharField(max_length=100)),
                ('ship_receiver_phone', models.CharField(max_length=15)),
                ('ship_adress', models.CharField(max_length=100)),
                ('ship_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer')),
                ('ship_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
