# Generated by Django 5.0.10 on 2024-12-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_orderitem_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao'), ('Đã hủy', 'Đã hủy'), ('Trả hàng', 'Trả hàng')], max_length=100),
        ),
    ]
