# Generated by Django 5.0.10 on 2024-12-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_order_order_total_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='ship_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.order'),
        ),
    ]
