# Generated by Django 5.0.10 on 2024-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_shipping_ship_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Chưa hoàn tất', 'Chưa hoàn tất'), ('Đang xử lý', 'Đang xử lý'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao'), ('Đã hủy', 'Đã hủy'), ('Trả hàng', 'Trả hàng')], max_length=100),
        ),
    ]
