# Generated by Django 5.0.10 on 2024-12-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_order_order_status_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_adress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_receiver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_receiver_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
